"""empty message

Revision ID: 8a33f285c415
Revises: 
Create Date: 2019-06-22 10:51:44.622315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a33f285c415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_key', sa.String(length=40), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('platform_id', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id')
    )
    op.create_index(op.f('ix_developers_dev_key'), 'developers', ['dev_key'], unique=True)
    op.create_index(op.f('ix_developers_username'), 'developers', ['username'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=150), nullable=True),
    sa.Column('channel', sa.String(length=150), nullable=True),
    sa.Column('token', sa.String(length=150), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    op.drop_table('channels')
    op.drop_index(op.f('ix_developers_username'), table_name='developers')
    op.drop_index(op.f('ix_developers_dev_key'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
